In [2]:
import pandas as pd

In [3]:
import numpy as np

In [6]:
a = np.arange(10)

In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [10]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a[1:3]

array([1, 2])

In [13]:
a2 = a.reshape(5,2)
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
a3 = a2[[0,1], 1]
a3

array([1, 3])

In [18]:
a4 = a[a>2]
a4

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
nda = np.arange(24).reshape(2, 3, 4)
nda

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
ndb = np.arange(12).reshape(3,4)
ndb

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
ndc = np.arange(4).reshape(4)
ndc

array([0, 1, 2, 3])

In [29]:
nda + ndb

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]])

In [30]:
nda + ndb - ndc

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]],

       [[12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]])

In [36]:
x = np.arange(6)

array([0, 1, 2, 3, 4, 5])